#!/bin/sh
aclocal
rm -rf ./autom4te.cache
rm -rf ./config.status
rm -rf `find . -name "Makefile.in"`
if hash glibtoolize 2>/dev/null ; then
    glibtoolize --force
else
    libtoolize --force
fi
autoconf
automake --add-missing
